[package]
name = "mulch2"
version = "0.1.0"
authors = ["Hazel Victoria Campbell <cargo@orezpraw.com>"]
edition = "2018"
workspace = ".."

[dependencies]
mulch2_macro = { path = "../mulch2_macro" }


[lib]
doctest = false

[features]
no-bounds-checks = []
